### PR TITLE
Do not use global websocket.DefaultDialer

### PR DESCRIPTION
**Pull request by ckaznocha**
This change makes it so that each forward gets its own dialer rather
then all sharing the global `websocket.DefaultDialer`. It allows `WebsocketTLSClientConfig` to
set a different TLS config than the one used in the http `RoundTripper`,
the TLS config in the http `RoundTripper` will still be used as a
fallback if one wasn't set by the user.

Adds the new `optSetter` `WebsocketNetDialContext` to set a custom
DialContet for WebSocket use.

Closes https://github.com/vulcand/oxy/issues/199

### CODE REVIEW

**Comment by clifton-sigsci** [comment]
OK this change doesn't address #125, the test is still failing on travis. On deeper inspection, I'm not really sure what `TestWebSocketNumGoRoutine` is trying to test. It just compares the number of goroutines before and after sending a WebSocket request. FWIW the logic under test here looks to be consistent but is covered by other tests.

**Comment by ckaznocha** [comment]
OK this change doesn't address #125, the test is still failing on travis. On deeper inspection, I'm not really sure what TestWebSocketNumGoRoutine is trying to test. It just compares the number of goroutines before and after sending a WebSocket request. FWIW the logic under test here looks to be consistent but is covered by other tests.

I've reverted the change to un-skip the test, all others still pass.

**Comment by emilevauge** [comment]
Maybe @juliens could help on this?

**Comment by ckaznocha** [comment]
Hey @juliens any chance you'll be able to take a look at this soon?

**Comment by ckaznocha** [comment]
This PR is getting stale but it's still an issue, any chance it can get reviewed? If there is some concern with the quality of the PR please let me know so I may address it.

**Comment by juliens** [comment]
Considering the refactoring #229 , the specific code for websocket has been removed so this PR cannot be merged.

**Pull request closed without merging**
