### PR TITLE
Drop internal logging lib, use logrus

### PR DESCRIPTION
**Pull request by agalitsyn**
Hi

Continue of https://github.com/vulcand/vulcand/pull/277 for using logrus lib as logging package across vulcand and libs

### CODE REVIEW

**Comment by agalitsyn** [comment]
Hi @klizhentas, could you review this please?

**Comment by horkhe** [comment]
@agalitsyn please rebase to the latest master.

**Comment by archisgore** [comment]
I'd like this change myself. I'll rebase and resubmit the PR to expedite it.

**Comment by archisgore** [comment]
I merged this in by rebasing against my fork. Thank you so much for this contribution! Going to help massively!

**Pull request closed without merging**
