### PR TITLE
Remove Hop-by-Hop headers when copying response. 

### LINKED ISSUE #43: Forwarder error on HTTP2 --> HTTP headers
Hello, 
If the oxy forwarder is used on HTTP2 protocol environments, the redirection does not work on Safari on Mac Os or IOs. The bug has been discovered using Traefik Proxy (see the link).

https://github.com/containous/traefik/issues/307#issuecomment-220918326

And seems to be related to the fact that the protocol version is manually overridden to http 1.1 , https://github.com/vulcand/oxy/blob/master/forward/fwd.go#L220

Any hints on which could be the best way to solve this?

### PR DESCRIPTION
**Pull request by pquerna**
Fixes #43

Currently have an internal fork of `forward` with a bunch of other changes, but this one is pretty obvious and can break things (see #43)...  

stdlib proxy also has similar code for removing hop by hop headers from responses:

https://github.com/golang/go/blob/go1.8.1/src/net/http/httputil/reverseproxy.go#L222-L224

### CODE REVIEW

**Comment by archisgore** [comment]
LGTM

**Comment by pquerna** [comment]
rebased

**Comment by klizhentas** [comment]
says something about:

"can't load package: package github.com/vulcand/oxy/forward: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus""

the first time I see this error

**Comment by russellhaering** [comment]
It relates to this: https://github.com/sirupsen/logrus/issues/553

It's a bit of a mess, everything needs to migrate to the lower-case import path, but for this PR it might make more sense to continue with the upper case one in oxy? Until all of vulcan can migrate over?

**Comment by klizhentas** [comment]
may be just get rid of sirupsen at all

**Comment by klizhentas** [comment]
meanwhile yes, we can continue with upper case in oxy

**Comment by archisgore** [comment]
LGTM

**Pull request merged**
