### PR TITLE
Enforce dep lock file consistency

### PR DESCRIPTION
**Pull request by ldez**
- enforce dep lock file consistency
- ~deleting cyclic references~ see #144

### CODE REVIEW

**Comment by ldez** [comment]
@archisgore could you take a look?

**Comment by archisgore** [comment]
Hah. I like how you're verifing it. And necessary. LGTM.

**Comment by ldez** [comment]
@archisgore As you can see, we (@Juliens  and me) contribute a lot to oxy
We work at Containous on Traefik.
Do you think it would be possible to add us in the oxy maintainers?
It would simplify our life a little :smiley: 

Thanks.

**Comment by archisgore** [comment]
I think someone from mailgun would have to do this. I'm a maintainer myself. I work at Polyverse, myself.

**Comment by ldez** [comment]
I will try to ping @klizhentas

**Pull request merged**
