### PR TITLE
Add layer 7 persistence / cookie sticky session support

### PR DESCRIPTION
**Pull request by owen**
I've been doing some work to try to get sticky sessions set up in Oxy's round robin.

To use, call `NewStickySession` with a cookie name.  Then when calling `rr.New`, pass `EnableStickySession` in to the options.  An server cookie (named as above) will be set and checked for future use.

This PR is against the base round robin only, for now.  I'm hoping to get an initial code review, and if you're interested, I'll keep fleshing this out against the rebalancing round robin.

### CODE REVIEW

**Comment by owen** [comment]
Hi all,

I've added similar logic to the rebalancing round robin as well.  Currently the design is such that once the HTTP cookie is set the connection will remain unchanged, but the performance of the server will feed back into the weights for new connections.

**Comment by owen** [comment]
Hey @klizhentas - I wanted to check to see if you have any interest in this PR.  If so, I'd be happy to extend it in any way you need.

**Comment by klizhentas** [comment]
at a first glance looks good, let me dig into it on the weekend

**Comment by owen** [comment]
Ugh - I forgot to branch this PR before I sent it in :(  I'm going to go ahead and close it since it includes Traefik specific changes.

**Pull request closed without merging**
